create role anon nologin; create role authenticated nologin;
alter default privileges in schema public grant all on tables to anon, authenticated; alter default privileges in schema public grant all on sequences to anon, authenticated; alter default privileges in schema public grant execute on functions to anon, authenticated;
create schema auth; create schema storage;
create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims', true),''),'{}')::jsonb $$;
create function auth.uid() returns uuid language sql stable as $$ select nullif(auth.jwt()->>'sub','')::uuid $$;
grant usage on schema auth, storage, public to anon, authenticated;
grant execute on all functions in schema auth to anon, authenticated;
create table storage.buckets(id text primary key, name text, public boolean, file_size_limit bigint, allowed_mime_types text[]);
create table storage.objects(id serial primary key, bucket_id text, name text, owner uuid);
alter table storage.objects enable row level security;
grant select, insert, update, delete on storage.objects to authenticated, anon;
grant usage on all sequences in schema storage to authenticated;
create table public.profiles(id uuid primary key, role text);
create table public.kader(id bigint primary key, name text, nr int, tw boolean, geb date, aktiv boolean default true, starker_fuss text, lieblingsposition text, foto_path text, foto_stadionheft_ok boolean default false);
create table public.kind_fanfacts(spieler_id bigint primary key, spitzname text, lieblingsverein text, lieblingsspieler text, foto_path text, gallery_optin boolean, adler_seit text, nummer_grund text, hobby text, lieblingsessen text, lieblingstier text, gross_werden text, lieblingsmusik text, lieblingsfilm text, fussball_erlebnis text, kann_gut text);
create table public.foto_consent(spieler_id bigint, intern boolean);
create table public.eltern_kinder(email text, spieler_id bigint);
create table public.kind_konto(uid uuid, spieler_id bigint, aktiv boolean);
create table public.termine(id bigint primary key, typ text, datum text, titel text, ort text, ergebnis text, spielform text, gegner text, uhrzeit time, uhrzeit_ende time, heim boolean, treffzeit text);
create table public.nominierungen(datum text primary key, data jsonb);
create table public.match_actions(id bigint primary key, datum text, spieler text, aktion text, created_at timestamptz default now());
create table public.turnier_spiele(id serial primary key, datum text, gegner text, tore int, gegentore int, created_at timestamptz default now());
create table public.termin_media(id bigint primary key, termin_id bigint, foto_path text, created_at timestamptz default now());
create table public.kabine_reporter(id bigint primary key, spieler_id bigint, frage text, antwort text, freigegeben boolean, created_at timestamptz default now());
create function public.is_trainer() returns boolean language sql stable security definer set search_path to 'public' as $$ select exists(select 1 from public.profiles where id = auth.uid() and role = 'trainer') $$;
create function public.ist_anonym() returns boolean language sql stable as $$ select coalesce((auth.jwt()->>'is_anonymous')::boolean,false) $$;
create function public.ist_mitglied() returns boolean language sql stable security definer set search_path to 'public' as $$ select public.is_trainer() or (not public.ist_anonym() and exists(select 1 from public.eltern_kinder e where lower(e.email)=lower(coalesce((select auth.jwt())->>'email','')))) or exists(select 1 from public.kind_konto k where k.uid=(select auth.uid()) and k.aktiv) $$;
create function public.sitzung_gueltig() returns boolean language sql stable security definer set search_path to 'public' as $$ select (select auth.uid()) is not null and public.ist_mitglied() $$;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all tables in schema public to anon;
