-- v734 (Auftragspaket Adler Nest, Abschnitt 8 „Porträt-Ablauf“, beschlossen 03.10.2026):
-- Porträt-Angaben werden über einen festen Ablauf eingeholt – Eltern bis Mittwoch 20 Uhr, Trainer bis Freitag
-- 20 Uhr vor dem Spieltag. Trainingsbeteiligung erscheint nur ab einer Schwelle (Standard 90 %) und nur aus der
-- tatsächlichen Anwesenheit (Tabelle anwesenheit), nie aus Zusagen.
-- Benachrichtigungen: portraet_push_faellig() entscheidet wie wiewars_push_faellig() in der Datenbank und merkt
-- sich jeden Versand; verschickt wird im vorhandenen 5-Minuten-Lauf rufe-push. Kein neuer Cron-Job.

-- 1) Einreichung je Porträt
create table if not exists public.portraet_einreichung (
  id bigint generated by default as identity primary key,
  spieler_id bigint not null references public.kader(id) on delete cascade,
  termin_id bigint references public.termine(id) on delete set null,   -- Spieltag, nach dem die Ausgabe erscheint
  ausgabe_id bigint references public.heft_ausgabe(id) on delete set null,
  status text not null default 'angefragt' check (status in ('angefragt','eingereicht','uebernommen')),
  einverstanden_am timestamptz,
  einverstanden_von uuid,
  privatfotos jsonb not null default '[]'::jsonb
    check (jsonb_typeof(privatfotos) = 'array' and jsonb_array_length(privatfotos) <= 2),
  frist_eltern timestamptz not null,
  frist_trainer timestamptz not null,
  erinnert_am timestamptz,
  angelegt_von uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.portraet_einreichung is 'v734: Porträt-Angaben je Kind und Ausgabe – Eltern lesen nur die Zeile ihres Kindes, solange nicht übernommen';
create unique index if not exists portraet_einreichung_offen_kind on public.portraet_einreichung(spieler_id) where status <> 'uebernommen';
create unique index if not exists portraet_einreichung_offen_termin on public.portraet_einreichung(termin_id) where status <> 'uebernommen' and termin_id is not null;

create or replace function public.portraet_einreichung_vor() returns trigger
language plpgsql set search_path to 'public' as $$
begin new.updated_at := now(); return new; end $$;
drop trigger if exists portraet_einreichung_vor on public.portraet_einreichung;
create trigger portraet_einreichung_vor before update on public.portraet_einreichung
  for each row execute function public.portraet_einreichung_vor();

alter table public.portraet_einreichung enable row level security;
revoke all on public.portraet_einreichung from anon;
grant select, insert, update, delete on public.portraet_einreichung to authenticated;
drop policy if exists pe_trainer on public.portraet_einreichung;
create policy pe_trainer on public.portraet_einreichung for all to authenticated
  using (public.is_trainer()) with check (public.is_trainer());
-- Eltern lesen die Zeile ihres Kindes, solange sie nicht übernommen ist. Geschrieben wird über portraet_einreichen().
drop policy if exists pe_eltern_lesen on public.portraet_einreichung;
create policy pe_eltern_lesen on public.portraet_einreichung for select to authenticated
  using (status <> 'uebernommen' and public.is_parent_of(spieler_id));
-- Das Kind selbst (Kinder-App) sieht, dass es im nächsten Heft ist – für den Hinweis auf die Porträtfragen.
drop policy if exists pe_kind_lesen on public.portraet_einreichung;
create policy pe_kind_lesen on public.portraet_einreichung for select to authenticated
  using (status <> 'uebernommen' and public.is_kind_selbst(spieler_id));

-- 2) Trainerstimmen – nur Trainer, nie an Eltern
create table if not exists public.portraet_trainerstimme (
  id bigint generated by default as identity primary key,
  einreichung_id bigint not null references public.portraet_einreichung(id) on delete cascade,
  trainer_id uuid not null default auth.uid(),
  stichpunkte text not null check (char_length(stichpunkte) between 1 and 600),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (einreichung_id, trainer_id)
);
comment on table public.portraet_trainerstimme is 'v734: 2–3 Stichpunkte je Trainer zum Porträtkind – nur Trainerteam';
create or replace function public.portraet_trainerstimme_vor() returns trigger
language plpgsql set search_path to 'public' as $$
begin new.trainer_id := auth.uid(); new.updated_at := now(); return new; end $$;
drop trigger if exists portraet_trainerstimme_vor on public.portraet_trainerstimme;
create trigger portraet_trainerstimme_vor before insert or update on public.portraet_trainerstimme
  for each row execute function public.portraet_trainerstimme_vor();
alter table public.portraet_trainerstimme enable row level security;
revoke all on public.portraet_trainerstimme from anon;
grant select, insert, update, delete on public.portraet_trainerstimme to authenticated;
drop policy if exists pts_trainer_lesen on public.portraet_trainerstimme;
create policy pts_trainer_lesen on public.portraet_trainerstimme for select to authenticated using (public.is_trainer());
drop policy if exists pts_trainer_eigene on public.portraet_trainerstimme;
create policy pts_trainer_eigene on public.portraet_trainerstimme for all to authenticated
  using (public.is_trainer() and trainer_id = auth.uid()) with check (public.is_trainer());

-- 3) Schwelle für die Trainingsbeteiligung (Einstellung im Trainerbereich, Standard 90 %)
alter table public.team_config add column if not exists portraet_schwelle smallint not null default 90;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'team_config_portraet_schwelle_check') then
    alter table public.team_config add constraint team_config_portraet_schwelle_check check (portraet_schwelle between 50 and 100);
  end if;
end $$;

-- 4) Kind festlegen: legt die Einreichung an und rechnet die Fristen (Mittwoch und Freitag vor dem Spieltag, 20 Uhr)
create or replace function public.portraet_anfragen(p_spieler bigint, p_termin bigint) returns public.portraet_einreichung
language plpgsql security definer set search_path to 'public' as $$
declare d date; mi date; fr date; neu public.portraet_einreichung;
begin
  if not public.is_trainer() then raise exception 'Nur Trainer'; end if;
  select datum::date into d from public.termine where id = p_termin and typ in ('spiel','turnier') and datum ~ '^\d{4}-\d{2}-\d{2}$';
  if d is null then raise exception 'Spieltag nicht gefunden'; end if;
  mi := d - ((extract(isodow from d)::int - 3 + 7) % 7); if mi >= d then mi := mi - 7; end if;
  fr := d - ((extract(isodow from d)::int - 5 + 7) % 7); if fr >= d then fr := fr - 7; end if;
  insert into public.portraet_einreichung(spieler_id, termin_id, frist_eltern, frist_trainer)
  values (p_spieler, p_termin, (mi + time '20:00') at time zone 'Europe/Berlin', (fr + time '20:00') at time zone 'Europe/Berlin')
  returning * into neu;
  return neu;
end $$;
revoke all on function public.portraet_anfragen(bigint, bigint) from public, anon;
grant execute on function public.portraet_anfragen(bigint, bigint) to authenticated;

-- 5) Eltern reichen ein oder ziehen das Einverständnis zurück. Rückgabe: Pfade, die nicht mehr gebraucht werden
--    (die App löscht sie im Speicher). Beim Rückzug verschwinden die Fotos auch aus der Ausgabe.
create or replace function public.portraet_einreichen(p_einreichung bigint, p_einverstanden boolean, p_privatfotos jsonb default '[]'::jsonb)
returns table(pfad text)
language plpgsql security definer set search_path to 'public' as $$
declare e public.portraet_einreichung; neu jsonb := '[]'::jsonb; f jsonb; alt text[];
begin
  select * into e from public.portraet_einreichung where id = p_einreichung;
  if e.id is null or not (public.is_trainer() or (public.is_parent_of(e.spieler_id) and e.status <> 'uebernommen')) then
    raise exception 'Keine Einreichung'; end if;
  alt := array(select x->>'pfad' from jsonb_array_elements(e.privatfotos) x);
  if p_einverstanden then
    if jsonb_typeof(coalesce(p_privatfotos,'[]'::jsonb)) <> 'array' or jsonb_array_length(coalesce(p_privatfotos,'[]'::jsonb)) > 2 then
      raise exception 'Höchstens 2 Privatfotos'; end if;
    for f in select * from jsonb_array_elements(coalesce(p_privatfotos,'[]'::jsonb)) loop
      if coalesce(f->>'pfad','') !~ ('^einreichung/' || e.id || '/[^/]+$') then raise exception 'Fremder Pfad'; end if;
      neu := neu || jsonb_build_object('pfad', f->>'pfad', 'unterschrift', left(coalesce(f->>'unterschrift',''), 80));
    end loop;
    update public.portraet_einreichung set privatfotos = neu, einverstanden_am = now(), einverstanden_von = auth.uid(),
      status = case when status = 'uebernommen' then status else 'eingereicht' end where id = e.id;
  else
    update public.portraet_einreichung set privatfotos = '[]'::jsonb, einverstanden_am = null, einverstanden_von = null,
      status = case when status = 'uebernommen' then status else 'angefragt' end where id = e.id;
    -- aus jeder Ausgabe entfernen, die diese Fotos trägt
    update public.heft_ausgabe a set portraet_privatfotos = coalesce((select jsonb_agg(x) from jsonb_array_elements(a.portraet_privatfotos) x
        where not (x->>'pfad' = any(alt))), '[]'::jsonb)
      where exists (select 1 from jsonb_array_elements(a.portraet_privatfotos) x where x->>'pfad' = any(alt));
  end if;
  return query select u from unnest(alt) u
    where not exists (select 1 from jsonb_array_elements(case when p_einverstanden then neu else '[]'::jsonb end) x where x->>'pfad' = u);
end $$;
revoke all on function public.portraet_einreichen(bigint, boolean, jsonb) from public, anon;
grant execute on function public.portraet_einreichen(bigint, boolean, jsonb) to authenticated;

-- 6) Privatfotos einer Ausgabe nur aus einer Einreichung mit Einverständnis (ersetzt die Prüfung aus v733).
--    Veröffentlichen markiert die Einreichung des Porträtkinds als übernommen.
create or replace function public.heft_ausgabe_vor() returns trigger
language plpgsql set search_path to 'public' as $$
declare f jsonb;
begin
  for f in select * from jsonb_array_elements(coalesce(new.portraet_privatfotos,'[]'::jsonb)) loop
    if jsonb_typeof(f) <> 'object' or coalesce(f->>'pfad','') = '' then raise exception 'Privatfoto ohne Datei'; end if;
    if not exists (select 1 from public.portraet_einreichung e
                    where e.spieler_id = new.portraet_spieler_id and e.einverstanden_am is not null
                      and exists (select 1 from jsonb_array_elements(e.privatfotos) x where x->>'pfad' = f->>'pfad')) then
      raise exception 'Privatfoto ohne Einverständnis der Familie';
    end if;
  end loop;
  if new.status = 'veroeffentlicht' and new.veroeffentlicht_am is null then new.veroeffentlicht_am := now(); end if;
  if new.status = 'entwurf' then new.veroeffentlicht_am := null; end if;
  new.updated_at := now();
  return new;
end $$;
create or replace function public.heft_ausgabe_nach() returns trigger
language plpgsql security definer set search_path to 'public' as $$
begin
  if new.status = 'veroeffentlicht' and new.portraet_spieler_id is not null then
    update public.portraet_einreichung set status = 'uebernommen', ausgabe_id = new.id
     where spieler_id = new.portraet_spieler_id and status <> 'uebernommen';
  end if;
  return null;
end $$;
drop trigger if exists heft_ausgabe_nach on public.heft_ausgabe;
create trigger heft_ausgabe_nach after insert or update of status, portraet_spieler_id on public.heft_ausgabe
  for each row execute function public.heft_ausgabe_nach();

-- 7) Speicher heft_media: Eltern schreiben und lesen nur unter einreichung/<id>/ ihrer eigenen offenen Einreichung
create or replace function public.heft_einreichung_eigen(p_name text) returns boolean
language sql stable security definer set search_path to 'public' as $$
  select p_name ~ '^einreichung/[0-9]+/[^/]+$' and exists (
    select 1 from public.portraet_einreichung e
     where e.id = split_part(p_name, '/', 2)::bigint and e.status <> 'uebernommen' and public.is_parent_of(e.spieler_id));
$$;
revoke all on function public.heft_einreichung_eigen(text) from public, anon;
grant execute on function public.heft_einreichung_eigen(text) to authenticated;
create or replace function public.heft_pfad_sichtbar(p_name text) returns boolean
language sql stable security definer set search_path to 'public' as $$
  select public.is_trainer() or public.heft_einreichung_eigen(p_name) or (public.sitzung_gueltig() and exists (
    select 1 from public.heft_ausgabe a
    where a.status = 'veroeffentlicht'
      and (a.titelbild_pfad = p_name or a.audio_pfad = p_name
           or exists (select 1 from jsonb_array_elements(a.portraet_privatfotos) e where e->>'pfad' = p_name))));
$$;
drop policy if exists "heft_media eltern schreiben" on storage.objects;
create policy "heft_media eltern schreiben" on storage.objects for insert to authenticated
  with check (bucket_id = 'heft_media' and public.heft_einreichung_eigen(name));
drop policy if exists "heft_media eltern loeschen" on storage.objects;
create policy "heft_media eltern loeschen" on storage.objects for delete to authenticated
  using (bucket_id = 'heft_media' and public.heft_einreichung_eigen(name));

-- 8) Trainingsbeteiligung: nur der Satz, und nur ab der Schwelle; gerechnet aus der Anwesenheitsliste der Saison.
--    Trainings ohne Liste zählen nicht; unter 6 erfassten Trainings kein Satz. Juli-Listen führen Vornamen statt IDs.
create or replace function public.portraet_beteiligung(p_spieler bigint) returns text
language plpgsql stable security definer set search_path to 'public' as $$
declare k public.kader; v_ab date; v_heute date := (now() at time zone 'Europe/Berlin')::date;
        n_erfasst int; n_dabei int; v_schwelle int;
begin
  if not public.is_trainer() then return null; end if;
  select * into k from public.kader where id = p_spieler; if k.id is null then return null; end if;
  v_ab := make_date(case when extract(month from v_heute) >= 7 then extract(year from v_heute)::int else extract(year from v_heute)::int - 1 end, 7, 1);
  select coalesce(max(portraet_schwelle), 90) into v_schwelle from public.team_config;
  with t as (
    select distinct te.datum from public.termine te
     where te.typ = 'training' and coalesce(te.platz_status,'') <> 'abgesagt'
       and te.datum ~ '^\d{4}-\d{2}-\d{2}$' and te.datum::date between v_ab and v_heute
  ), e as (
    select coalesce(a.data -> (k.id::text), a.data -> k.name) eintrag
      from t join public.anwesenheit a on a.datum = t.datum
  )
  select count(*) filter (where eintrag is not null), count(*) filter (where (eintrag->>'da')::boolean)
    into n_erfasst, n_dabei from e;
  if n_erfasst < 6 or n_dabei * 100 < v_schwelle * n_erfasst then return null; end if;
  return case when n_dabei = n_erfasst then 'bei jedem Training dabei' else 'bei fast jedem Training dabei' end;
end $$;
revoke all on function public.portraet_beteiligung(bigint) from public, anon;
grant execute on function public.portraet_beteiligung(bigint) to authenticated;

-- 9) Benachrichtigungen: genau einmal je Konto und Art (Protokoll), Ruhezeit je Konto wie v705.
create table if not exists public.portraet_push_log (
  einreichung_id bigint not null references public.portraet_einreichung(id) on delete cascade,
  user_id uuid not null,
  art text not null check (art in ('eltern_anfrage','eltern_erinnerung','trainer_hinweis','trainer_erinnerung')),
  gesendet_am timestamptz not null default now(),
  primary key (einreichung_id, user_id, art)
);
comment on table public.portraet_push_log is 'v734: welche Porträt-Benachrichtigung an wen ging – jede genau einmal';
alter table public.portraet_push_log enable row level security;
revoke all on public.portraet_push_log from anon, authenticated;

create or replace function public.portraet_push_faellig(p_jetzt timestamptz default now())
returns table(user_id uuid, titel text, text text, url text)
language plpgsql security definer set search_path = public as $$
#variable_conflict use_column
declare v_lokal timestamp := p_jetzt at time zone 'Europe/Berlin';
begin
  return query
  with e as (
    select pe.*, k.name kind, (pe.frist_trainer at time zone 'Europe/Berlin')::date fr_tag
      from portraet_einreichung pe join kader k on k.id = pe.spieler_id
     where pe.status <> 'uebernommen' and p_jetzt < pe.frist_trainer
  ), eltern as (
    select distinct e.id eid, e.kind, e.status, e.frist_eltern, u.id uid
      from e join eltern_kinder ek on ek.spieler_id = e.spieler_id
      join auth.users u on lower(u.email) = lower(ek.email)
  ), trainer as (
    select e.id eid, e.kind, e.fr_tag, p.id uid,
           exists (select 1 from portraet_trainerstimme s where s.einreichung_id = e.id and s.trainer_id = p.id) hat_stimme
      from e cross join profiles p where p.role = 'trainer'
  ), kand as (
    select el.eid, el.uid, 'eltern_anfrage'::text art, el.kind from eltern el
     where el.status = 'angefragt'
    union all
    select el.eid, el.uid, 'eltern_erinnerung', el.kind from eltern el
     where el.status = 'angefragt' and p_jetzt >= el.frist_eltern
       and exists (select 1 from portraet_push_log l where l.einreichung_id = el.eid and l.user_id = el.uid
                    and l.art = 'eltern_anfrage' and l.gesendet_am < el.frist_eltern)
    union all
    select tr.eid, tr.uid, 'trainer_hinweis', tr.kind from trainer tr
     where v_lokal >= (tr.fr_tag - 4) + time '09:00'                -- ab Montag 9 Uhr der Spieltagswoche
    union all
    select tr.eid, tr.uid, 'trainer_erinnerung', tr.kind from trainer tr
     where not tr.hat_stimme and v_lokal >= tr.fr_tag + time '08:00'  -- Freitagmorgen
  ), bereit as (
    select k.* from kand k
     where exists (select 1 from push_subscriptions ps where ps.user_id = k.uid)
       and not public.push_ruht(k.uid, p_jetzt)
  ), gemerkt as (
    insert into portraet_push_log(einreichung_id, user_id, art)
    select b.eid, b.uid, b.art from bereit b
    on conflict do nothing
    returning portraet_push_log.einreichung_id, portraet_push_log.user_id, portraet_push_log.art
  )
  select b.uid,
         case b.art when 'eltern_anfrage' then '🪺 ' || split_part(b.kind,' ',1) || ' ist im nächsten Adler Nest'
                    when 'eltern_erinnerung' then '🪺 Noch Zeit fürs Porträt'
                    when 'trainer_hinweis' then '🪺 Porträt: ' || split_part(b.kind,' ',1)
                    else '🪺 Deine Stimme fürs Porträt fehlt' end,
         case b.art when 'eltern_anfrage' then 'Füllt bis Mittwoch 20 Uhr den kurzen Porträt-Bogen aus – Fan-Fakten und auf Wunsch bis zu zwei Fotos.'
                    when 'eltern_erinnerung' then 'Der Porträt-Bogen ist noch offen. Ein paar Angaben reichen schon.'
                    when 'trainer_hinweis' then 'Bis Freitag 20 Uhr: zwei, drei Stichpunkte – was das Kind auszeichnet, woran es arbeitet.'
                    else 'Bis heute 20 Uhr: zwei, drei Stichpunkte zum Porträtkind.' end,
         case when b.art like 'eltern%' then './eltern/?portal&nest=bogen' else './trainer/?nest=ablauf' end
    from bereit b
    join gemerkt g on g.einreichung_id = b.eid and g.user_id = b.uid and g.art = b.art;
end $$;
revoke all on function public.portraet_push_faellig(timestamptz) from public, anon, authenticated;
grant execute on function public.portraet_push_faellig(timestamptz) to service_role;

-- 10) Trainerstimmen reichen in die Hüllfunktion der Leseansicht NICHT hinein (heft_ausgabe_lesen bleibt unverändert).
