-- Paket 2 „Unsere Regeln" (doku/auftrag-adler-luecken).
--
-- Der Fairplay-Codex spricht die ELTERN an: elf Punkte, Erwachsenensprache, im
-- Eltern-Bereich. Für die Kinder gab es nichts Vergleichbares – in der Kabine stand
-- nirgends, wofür diese Mannschaft steht.
--
-- Bewusst eine eigene Tabelle und keine Spalte an fairplay_regeln: die Kindersätze
-- sind kein gekürzter Elterncodex, sondern dessen Gegenstück. Sie ändern sich
-- unabhängig und dürfen von jedem gelesen werden.
--
-- RLS wie bei den übrigen trainerpflegbaren Inhalten, mit einem Unterschied: gelesen
-- werden darf auch ohne Anmeldung. Der Inhalt ist unbedenklich (sechs Sätze über
-- Fairness, keine personenbezogenen Daten), und die Kabine soll ihn zeigen können,
-- ohne an einer Sitzung zu hängen. Geschrieben wird nur von angemeldeten Trainern.

create table if not exists public.kinder_codex (
  id          bigint generated by default as identity primary key,
  nr          integer not null default 0,          -- Reihenfolge, wie sie in der Kabine steht
  satz        text    not null,
  aktiv       boolean not null default true,
  created_at  timestamptz not null default now()
);

comment on table public.kinder_codex is
  'Unsere Regeln – der Codex in Kindersprache für die Kabine. Höchstens sechs aktive Sätze; gepflegt vom Trainerteam unter Eltern & Kinder.';

create index if not exists kinder_codex_nr_idx on public.kinder_codex (aktiv, nr, id);

alter table public.kinder_codex enable row level security;

drop policy if exists "kc read alle" on public.kinder_codex;
create policy "kc read alle" on public.kinder_codex
  for select to anon, authenticated using (true);

drop policy if exists "kc trainer all" on public.kinder_codex;
create policy "kc trainer all" on public.kinder_codex
  for all to authenticated using (public.is_trainer()) with check (public.is_trainer());

-- Startinhalt aus dem Auftragspaket. Satz 4 ist der Zuruf aus dem Trainerkonzept –
-- er gehört hierher, weil die Kinder ihn ohnehin kennen. Nur beim ersten Anlegen:
-- ein späterer Lauf darf die Sätze des Trainers nicht überschreiben.
insert into public.kinder_codex (nr, satz, aktiv)
select * from (values
  (0, 'Jeder spielt.',                                  true),
  (1, 'Wir jubeln für jedes Tor — auch für das vom anderen.', true),
  (2, 'Wer verliert, gibt trotzdem die Hand.',          true),
  (3, 'Erst geht’s nicht. Dann geht’s.',            true),
  (4, 'Der Schiri hat recht.',                          true),
  (5, 'Wir räumen gemeinsam auf.',                      true)
) as v(nr, satz, aktiv)
where not exists (select 1 from public.kinder_codex);
