-- v751 · „Mein Training“: Kinder gestalten in der Kabine ein Training und schicken es dem Trainerteam
-- Charles 04.10.: „Es soll auch ein Training theoretisch gestalten können. Wie für einen Trainer, aber
-- kindgerecht.“ Kachel: „Auch an Trainer schicken“.
--
-- Ein Training hat bis zu drei Teile (aufwaermen, uebung, abschluss). Jeder Teil nennt eine Übung aus der
-- Bibliothek (Name) ODER eine eigene Skizze vom Taktikbrett (Stand: Form, Steine, Striche) und die Minuten.
-- Kein Freitext: Im Kinder-Modus gibt es kein Textfeld. Auf eigenen Skizzen können Vornamen von Mitspielern
-- stehen (v750) – das sieht nur das Trainerteam und die eigene Familie.
--
-- Rechte: schreiben das Kindergerät für sich selbst (nur mit Appzeit übrig) und Eltern für das eigene Kind;
-- lesen dieselben und das Trainerteam; ändern (gesehen/Danke) nur Trainer; löschen Trainer und die eigene
-- Familie. Höchstens 20 offene Trainings je Kind, damit niemand das Postfach flutet.

create table if not exists public.kind_training (
  id bigint generated by default as identity primary key,
  spieler_id bigint not null references public.kader(id) on delete cascade,
  teile jsonb not null check (jsonb_typeof(teile) = 'array' and jsonb_array_length(teile) between 1 and 3
                              and octet_length(teile::text) <= 60000),
  created_at timestamptz not null default now(),
  gesehen_am timestamptz,
  danke_am timestamptz
);
comment on table public.kind_training is 'v751: Trainingsideen der Kinder aus der Kabine („Mein Training“). Bis zu drei Teile mit Übungsname oder eigener Skizze und Minuten; kein Freitext.';
create index if not exists kind_training_spieler on public.kind_training(spieler_id, created_at desc);
alter table public.kind_training enable row level security;

-- Form der Teile prüfen: art aus der Liste, Minuten 1–30, genau eines von uebung/brett
create or replace function public.kind_training_ok(p jsonb) returns boolean
language sql immutable set search_path to 'public' as $$
  select coalesce(bool_and(
           (t->>'art') in ('aufwaermen','uebung','abschluss')
       and (t->>'minuten') ~ '^[0-9]{1,2}$' and (t->>'minuten')::int between 1 and 30
       and ((t ? 'uebung' and jsonb_typeof(t->'uebung')='string' and length(t->>'uebung') between 1 and 160 and not t ? 'brett')
         or (t ? 'brett' and jsonb_typeof(t->'brett')='object' and not t ? 'uebung'))
         ), false)
    from jsonb_array_elements(p) t;
$$;
alter table public.kind_training drop constraint if exists kind_training_teile_ok;
alter table public.kind_training add constraint kind_training_teile_ok check (public.kind_training_ok(teile));

create or replace function public.kind_training_vor_insert() returns trigger
language plpgsql security definer set search_path to 'public' as $$
begin
  if (select count(*) from kind_training k where k.spieler_id = new.spieler_id and k.gesehen_am is null) >= 20
    then raise exception 'zu viele offene Trainings'; end if;
  new.created_at := now(); new.gesehen_am := null; new.danke_am := null;
  return new;
end $$;
drop trigger if exists kind_training_vor on public.kind_training;
create trigger kind_training_vor before insert on public.kind_training for each row execute function public.kind_training_vor_insert();

drop policy if exists kt_lesen on public.kind_training;
create policy kt_lesen on public.kind_training for select to authenticated
  using (public.is_trainer() or public.is_parent_of(spieler_id) or public.is_kind_selbst(spieler_id));
drop policy if exists kt_schreiben on public.kind_training;
create policy kt_schreiben on public.kind_training for insert to authenticated
  with check (public.is_parent_of(spieler_id) or (public.is_kind_selbst(spieler_id) and public.kind_zeit_uebrig()));
drop policy if exists kt_aendern on public.kind_training;
create policy kt_aendern on public.kind_training for update to authenticated
  using (public.is_trainer()) with check (public.is_trainer());
drop policy if exists kt_loeschen on public.kind_training;
create policy kt_loeschen on public.kind_training for delete to authenticated
  using (public.is_trainer() or public.is_parent_of(spieler_id) or public.is_kind_selbst(spieler_id));
revoke all on public.kind_training from anon;
grant select, insert, update, delete on public.kind_training to authenticated;
-- Trainer ändern nur gesehen/Danke
revoke update on public.kind_training from authenticated;
grant update (gesehen_am, danke_am) on public.kind_training to authenticated;
