-- v756 · Adler Nest: Teil-Link für die Hördatei (Nachtrag PDF-Export, Beschluss 18, 04.10.2026)
-- Eltern geben das PDF einer Ausgabe an andere Familien weiter. Die Hördatei spielt in PDF-Ansichten auf dem Handy nicht,
-- deshalb trägt das PDF einen Link zu einer Hörseite (?hoeren=<token>): ohne Login, 30 Tage gültig, vom Trainerteam
-- vorher zurückziehbar. Der Link liefert genau die Hördatei der EINEN Ausgabe, keine weiteren Inhalte.
--
-- Zugriff:
--   · Tabelle heft_audio_link: nur Trainer lesen und schreiben; anon nichts.
--   · heft_audio_link_neu / _zurueckziehen: nur Trainer (security definer, prüft is_trainer()).
--   · heft_audio_abrufen(token): nur die Edge Function heft-audio (service_role). Sie bekommt den Pfad der Hördatei
--     NUR bei gültigem, nicht abgelaufenem, nicht zurückgezogenem Token UND veröffentlichter Ausgabe und gibt eine
--     signierte Adresse mit höchstens 600 Sekunden zurück. Jeder Abruf prüft neu: Zurückziehen wirkt nach höchstens
--     10 Minuten, auch auf bereits ausgegebene Adressen.
-- Der Token besteht aus zwei zufälligen UUIDs (2 × 122 Bit, 64 Hexzeichen).

create table if not exists public.heft_audio_link (
  id bigint generated by default as identity primary key,
  ausgabe_id bigint not null references public.heft_ausgabe(id) on delete cascade,
  token text not null unique default (replace(gen_random_uuid()::text,'-','') || replace(gen_random_uuid()::text,'-','')),
  gueltig_bis timestamptz not null default (now() + interval '30 days'),
  zurueckgezogen_am timestamptz,
  created_at timestamptz not null default now(),
  constraint heft_audio_link_token_form check (token ~ '^[0-9a-f]{64}$')
);
comment on table public.heft_audio_link is 'v756: Teil-Link für die Hördatei einer Ausgabe (Hörseite ?hoeren=<token>), 30 Tage, zurückziehbar. Nur Trainer; öffentlich ist allein heft_audio_abrufen über die Edge Function heft-audio.';
create index if not exists heft_audio_link_ausgabe on public.heft_audio_link(ausgabe_id, created_at desc);
alter table public.heft_audio_link enable row level security;
drop policy if exists hal_trainer on public.heft_audio_link;
create policy hal_trainer on public.heft_audio_link for all to authenticated using (public.is_trainer()) with check (public.is_trainer());
revoke all on public.heft_audio_link from anon;
grant select, insert, update, delete on public.heft_audio_link to authenticated;

-- Neuer Link: zieht einen noch aktiven Link derselben Ausgabe zurück (mehr als ein aktiver je Ausgabe ist nicht nötig)
create or replace function public.heft_audio_link_neu(p_ausgabe bigint)
returns table(token text, gueltig_bis timestamptz)
language plpgsql security definer set search_path to 'public' as $$
declare v_audio text;
begin
  if not public.is_trainer() then raise exception 'nur Trainer' using errcode = '42501'; end if;
  select a.audio_pfad into v_audio from public.heft_ausgabe a where a.id = p_ausgabe;
  if not found then raise exception 'Ausgabe nicht gefunden'; end if;
  if v_audio is null or v_audio = '' then raise exception 'Diese Ausgabe hat keine Hördatei'; end if;
  update public.heft_audio_link l set zurueckgezogen_am = now() where l.ausgabe_id = p_ausgabe and l.zurueckgezogen_am is null;
  return query insert into public.heft_audio_link(ausgabe_id) values (p_ausgabe) returning heft_audio_link.token, heft_audio_link.gueltig_bis;
end $$;
revoke all on function public.heft_audio_link_neu(bigint) from public, anon;
grant execute on function public.heft_audio_link_neu(bigint) to authenticated;

create or replace function public.heft_audio_link_zurueckziehen(p_ausgabe bigint) returns int
language plpgsql security definer set search_path to 'public' as $$
declare n int;
begin
  if not public.is_trainer() then raise exception 'nur Trainer' using errcode = '42501'; end if;
  update public.heft_audio_link l set zurueckgezogen_am = now() where l.ausgabe_id = p_ausgabe and l.zurueckgezogen_am is null;
  get diagnostics n = row_count; return n;
end $$;
revoke all on function public.heft_audio_link_zurueckziehen(bigint) from public, anon;
grant execute on function public.heft_audio_link_zurueckziehen(bigint) to authenticated;

-- Abruf mit Token: nur service_role (Edge Function heft-audio). Liefert höchstens EINE Zeile: die Hördatei dieser Ausgabe.
create or replace function public.heft_audio_abrufen(p_token text)
returns table(pfad text, nummer int, sekunden int)
language sql stable security definer set search_path to 'public' as $$
  select a.audio_pfad, a.nummer, a.audio_sekunden
    from public.heft_audio_link l
    join public.heft_ausgabe a on a.id = l.ausgabe_id
   where l.token = p_token
     and l.zurueckgezogen_am is null
     and l.gueltig_bis > now()
     and a.status = 'veroeffentlicht'
     and a.audio_pfad is not null and a.audio_pfad <> ''
   limit 1;
$$;
revoke all on function public.heft_audio_abrufen(text) from public, anon, authenticated;
grant execute on function public.heft_audio_abrufen(text) to service_role;
