-- v569 · Vier Spielform-Ordnungen im Spaltenkommentar, Skalierung 8/10/12/14 nachziehen
--
-- 1) Der Kommentar: v568 hatte die Datei 20260916_vorlagen_ordnung_spielformen.sql
--    vorgesehen, sie wurde nie eingespielt (Kommentar stand noch auf sechs Werten).
--    Diese Migration setzt ihn neu, jetzt mit vier Spielform-Ordnungen – „3+1 und FUNiño"
--    ist die Einheit mit drei Feldern nebeneinander (L4-8).
-- 2) Die Skalierung: der Kader der U9 I hat hoechstens 14 Kinder. Die acht Einheiten aus
--    v568 tragen in uebungen/vorlagen.json seit v569 die Schluessel 8/10/12/14 statt
--    8/12/16. Der Abgleich beim Oeffnen legt nur NEUE Zeilen an und ruehrt bestehende
--    nie an, und die Tabelle hat per RLS kein UPDATE aus der App – die acht Zeilen, die
--    seit v568 in der Datenbank stehen, muessen deshalb hier nachgezogen werden. Die
--    Werte sind wortgleich mit vorlagen-nachtrag.json / vorlagen-nachtrag-kombi.json
--    (Skript-erzeugt, nicht abgetippt). L4-8 ist neu und kommt ueber den Abgleich.

comment on column public.trainingsvorlagen.ordnung is
  'Wie die Mannschaft im Spiel steht: 1 gegen 1 · 2 gegen 2 · Dreieck (3 gegen 3) · Raute (4 gegen 4) · 3+1 · FUNiño · 3+1 gegen FUNiño · 3+1 und FUNiño · Ueberzahl · ohne Gegner. NULL = keine besondere.';

update public.trainingsvorlagen set skalierung = '{"8": "Ein Feld, zwei Teams zu je 4 (3+1), keine Rotation; in den Hauptteilen 1 und 2 zwei Gruppen zu 4 mit den leichteren Varianten (3+1 gegen 1 bzw. ohne Wartende).", "10": "Hauptteile 1 und 2: zwei Gruppen zu 5, an jeder Station rotiert ein Kind nach jedem Durchgang ein. Hauptteil 3 und Turnier: 3+1 gegen 3+1 mit je einem Wechsler – im Plan Feld 2 weglassen.", "12": "Hauptteile 1 und 2: zwei Gruppen zu 6, je Halbfeld eine Station (ist nur ein Jugendtor frei, spielt Station 2 auf zwei Minitore mit Torwart ohne Hände). Hauptteil 3 und Turnier: ein Feld, zwei Teams zu 6 (3+1 plus 2 Rotation) – im Plan Feld 2 weglassen.", "14": "Hauptteile 1 und 2: zwei Gruppen zu 7, an jeder Station rotieren zwei Kinder ein. Hauptteil 3 und Turnier: zwei Felder, 3+1 gegen 3+1 mit Wechslern; fehlt für das zweite Feld das Jugendtor, ersetzen es zwei Minitore mit Torwart ohne Hände in der Schusszone."}'::jsonb, stand = '2026-09-18-1'
  where name = 'L4-6 3+1 – Adler: breit werden, der Torwart spielt mit';

update public.trainingsvorlagen set skalierung = '{"8": "Ein Feld, zwei Teams zu je 4 (3+1), keine Rotation; in den Hauptteilen 1 und 2 zwei Gruppen zu 4 mit den leichteren Varianten (3+1 gegen 1 bzw. ohne Wartende).", "10": "Hauptteile 1 und 2: zwei Gruppen zu 5, an jeder Station rotiert ein Kind nach jedem Durchgang ein. Hauptteil 3 und Turnier: 3+1 gegen 3+1 mit je einem Wechsler – im Plan Feld 2 weglassen.", "12": "Hauptteile 1 und 2: zwei Gruppen zu 6, je Halbfeld eine Station (ist nur ein Jugendtor frei, spielt Station 2 auf zwei Minitore mit Torwart ohne Hände). Hauptteil 3 und Turnier: ein Feld, zwei Teams zu 6 (3+1 plus 2 Rotation) – im Plan Feld 2 weglassen.", "14": "Hauptteile 1 und 2: zwei Gruppen zu 7, an jeder Station rotieren zwei Kinder ein. Hauptteil 3 und Turnier: zwei Felder, 3+1 gegen 3+1 mit Wechslern; fehlt für das zweite Feld das Jugendtor, ersetzen es zwei Minitore mit Torwart ohne Hände in der Schusszone."}'::jsonb, stand = '2026-09-18-1'
  where name = 'L5-4 3+1 – Raute ohne Aufpasser: wo stehe ich?';

update public.trainingsvorlagen set skalierung = '{"8": "Ein Feld, zwei Teams zu je 4 (3+1), keine Rotation; in den Hauptteilen 1 und 2 zwei Gruppen zu 4 mit den leichteren Varianten (3+1 gegen 1 bzw. ohne Wartende).", "10": "Hauptteile 1 und 2: zwei Gruppen zu 5, an jeder Station rotiert ein Kind nach jedem Durchgang ein. Hauptteil 3 und Turnier: 3+1 gegen 3+1 mit je einem Wechsler – im Plan Feld 2 weglassen.", "12": "Hauptteile 1 und 2: zwei Gruppen zu 6, je Halbfeld eine Station (ist nur ein Jugendtor frei, spielt Station 2 auf zwei Minitore mit Torwart ohne Hände). Hauptteil 3 und Turnier: ein Feld, zwei Teams zu 6 (3+1 plus 2 Rotation) – im Plan Feld 2 weglassen.", "14": "Hauptteile 1 und 2: zwei Gruppen zu 7, an jeder Station rotieren zwei Kinder ein. Hauptteil 3 und Turnier: zwei Felder, 3+1 gegen 3+1 mit Wechslern; fehlt für das zweite Feld das Jugendtor, ersetzen es zwei Minitore mit Torwart ohne Hände in der Schusszone."}'::jsonb, stand = '2026-09-18-1'
  where name = 'L6-3 3+1 – Igel: die Flitzer schließen die Lücke';

update public.trainingsvorlagen set skalierung = '{"8": "Hauptteile 1 und 2: zwei Gruppen zu 4, Stationen mit der leichteren Variante, höchstens 2 gegen 2. Hauptteil 3: ein FUNiño-Feld 3 gegen 3 plus 2 Rotation – Feld 2 weglassen.", "10": "Hauptteile 1 und 2: zwei Gruppen zu 5, an jeder Station rotiert ein Kind ein. Hauptteil 3 und Turnier: 3 gegen 3 mit je einem Wechsler auf einem Feld – im Plan Feld 2 weglassen.", "12": "Zwei Gruppen zu 6, je Gruppe ein FUNiño-Feld. Hauptteil 3 auf beiden Feldern 3 gegen 3. Turnier: vier Teams zu 3 auf zwei Feldern, Gewinner rückt ein Feld auf.", "14": "Hauptteile 1 und 2: zwei Gruppen zu 7, an jeder Station rotieren zwei Kinder ein. Hauptteil 3 und Turnier: zwei Felder 3 gegen 3 mit je einem Wechsler; das zweite Feld mit vier Hütchentoren, nach jedem Durchgang Felder tauschen."}'::jsonb, stand = '2026-09-18-1'
  where name = 'L4-7 FUNiño – der Aufpasser verteilt';

update public.trainingsvorlagen set skalierung = '{"8": "Hauptteile 1 und 2: zwei Gruppen zu 4, Stationen mit der leichteren Variante, höchstens 2 gegen 2. Hauptteil 3: ein FUNiño-Feld 3 gegen 3 plus 2 Rotation – Feld 2 weglassen.", "10": "Hauptteile 1 und 2: zwei Gruppen zu 5, an jeder Station rotiert ein Kind ein. Hauptteil 3 und Turnier: 3 gegen 3 mit je einem Wechsler auf einem Feld – im Plan Feld 2 weglassen.", "12": "Zwei Gruppen zu 6, je Gruppe ein FUNiño-Feld. Hauptteil 3 auf beiden Feldern 3 gegen 3. Turnier: vier Teams zu 3 auf zwei Feldern, Gewinner rückt ein Feld auf.", "14": "Hauptteile 1 und 2: zwei Gruppen zu 7, an jeder Station rotieren zwei Kinder ein. Hauptteil 3 und Turnier: zwei Felder 3 gegen 3 mit je einem Wechsler; das zweite Feld mit vier Hütchentoren, nach jedem Durchgang Felder tauschen."}'::jsonb, stand = '2026-09-18-1'
  where name = 'L5-5 FUNiño – links, Mitte, rechts';

update public.trainingsvorlagen set skalierung = '{"8": "Hauptteile 1 und 2: zwei Gruppen zu 4, Stationen mit der leichteren Variante, höchstens 2 gegen 2. Hauptteil 3: ein FUNiño-Feld 3 gegen 3 plus 2 Rotation – Feld 2 weglassen.", "10": "Hauptteile 1 und 2: zwei Gruppen zu 5, an jeder Station rotiert ein Kind ein. Hauptteil 3 und Turnier: 3 gegen 3 mit je einem Wechsler auf einem Feld – im Plan Feld 2 weglassen.", "12": "Zwei Gruppen zu 6, je Gruppe ein FUNiño-Feld. Hauptteil 3 auf beiden Feldern 3 gegen 3. Turnier: vier Teams zu 3 auf zwei Feldern, Gewinner rückt ein Feld auf.", "14": "Hauptteile 1 und 2: zwei Gruppen zu 7, an jeder Station rotieren zwei Kinder ein. Hauptteil 3 und Turnier: zwei Felder 3 gegen 3 mit je einem Wechsler; das zweite Feld mit vier Hütchentoren, nach jedem Durchgang Felder tauschen."}'::jsonb, stand = '2026-09-18-1'
  where name = 'L6-4 FUNiño – einer drängt, zwei schützen';

update public.trainingsvorlagen set skalierung = '{"8": "Hauptteile 1 und 2: zwei Gruppen zu 4 mit den leichteren Varianten. Hauptteil 3 und Turnier: 3+1 gegen 3, ein Wechsler – im Plan Feld 2 weglassen.", "10": "Hauptteile 1 und 2: zwei Gruppen zu 5, an jeder Station rotiert ein Kind ein. Hauptteil 3 und Turnier: 3+1 gegen 3 mit je einem Wechsler – im Plan Feld 2 weglassen.", "12": "Hauptteile 1 und 2: zwei Gruppen zu 6, Station 1 auf der Jugendtor-Hälfte, Station 2 auf der Minitor-Hälfte desselben Feldes. Hauptteil 3 und Turnier: 3+1 mit 2 Wechslern gegen 3 mit 3 Wechslern – im Plan Feld 2 weglassen.", "14": "Hauptteile 1 und 2: zwei Gruppen zu 7, an jeder Station rotieren zwei Kinder ein. Hauptteil 3 und Turnier: zwei Felder – sieben Kinder auf dem Kombi-Feld (3+1 gegen 3), sieben auf einem zweiten Feld mit vier Hütchentoren (FUNiño 3 gegen 3 mit einem Wechsler); nach der Hälfte Felder tauschen."}'::jsonb, stand = '2026-09-18-1'
  where name = 'L5-6 3+1 gegen FUNiño – große und kleine Tore';

update public.trainingsvorlagen set skalierung = '{"8": "Hauptteile 1 und 2: zwei Gruppen zu 4 mit den leichteren Varianten (Igel gegen zwei, FUNiño 2 gegen 2 ohne Rotation). Hauptteil 3 und Turnier: 3+1 gegen 3, ein Wechsler – im Plan Feld 2 weglassen.", "10": "Hauptteile 1 und 2: zwei Gruppen zu 5, an jeder Station rotiert ein Kind ein. Hauptteil 3 und Turnier: 3+1 gegen 3 mit je einem Wechsler – im Plan Feld 2 weglassen.", "12": "Hauptteile 1 und 2: zwei Gruppen zu 6, Station 1 auf der Jugendtor-Hälfte, Station 2 auf der Minitor-Hälfte desselben Feldes (zwei Minitore an der Grundlinie, zwei Hütchentore an der Mittellinie). Hauptteil 3 und Turnier: 3+1 mit 2 Wechslern gegen 3 mit 3 Wechslern – im Plan Feld 2 weglassen.", "14": "Hauptteile 1 und 2: zwei Gruppen zu 7, an jeder Station rotieren zwei Kinder ein. Hauptteil 3 und Turnier: zwei Felder – sieben Kinder auf dem Kombi-Feld (3+1 gegen 3), sieben auf einem zweiten Feld mit vier Hütchentoren (FUNiño 3 gegen 3 mit einem Wechsler); nach der Hälfte Felder tauschen."}'::jsonb, stand = '2026-09-18-1'
  where name = 'L6-5 3+1 gegen FUNiño – zwei Arten, den Ball zurückzuholen';
