-- v736 · Adler-Ruf: 5.000 Zeichen und Anhänge (doku/auftrag-rufe-anhaenge/Auftragspaket_Rufe_Anhaenge.md)
-- Am 04.10.2026 von Charles im SQL-Editor eingespielt; ausgeliefert mit App-Version v748 (gebaut als v736).
-- Lokal gegen ein Postgres 16 mit tests/sql/supabase-attrappe.sql geprüft (tests/sql/v736-rufe-anhaenge.sql).
--
-- 1. Zeichenlimit 2.000 → 5.000 (CHECK und rufe_bearbeiten; das Eingabefeld zieht der Client nach).
--    rufe_push_faellig kürzt ohnehin auf 110 Zeichen, die Suche (ilike) kennt keine feste Länge.
-- 2. Privater Bucket rufe-anhang: 10 MB, Bilder, PDF, Word, Excel, PowerPoint – keine Makroformate, kein SVG/HTML.
-- 3. Tabelle rufe_anhang mit RLS: lesen wie rn_lesen, schreiben nur der Autor (höchstens vier je Ruf), ändern nie,
--    löschen nur Trainer.
-- 4. rufe_senden: Ruf und Anhänge in EINEM Aufruf (security invoker – der Trigger rufe_vor_insert setzt den Autor
--    weiter aus auth.uid(), die RLS gilt wie beim direkten Schreiben). Scheitert ein Anhang, gibt es keinen Ruf.
-- 5. rufe_anhaenge_loeschen: Trainer entfernt Zeilen (die Dateien löscht die App über die Storage-API) und
--    markiert den Ruf mit anhang_entfernt_am („Anhang entfernt“).

-- ── 1. Zeichenlimit ─────────────────────────────────────────────────────────────
alter table public.rufe_nachricht drop constraint if exists rufe_nachricht_text_check;
alter table public.rufe_nachricht add constraint rufe_nachricht_text_check
  check (length(trim(both from text)) >= 1 and length(trim(both from text)) <= 5000);
alter table public.rufe_nachricht add column if not exists anhang_entfernt_am timestamptz;

create or replace function public.rufe_bearbeiten(p_id bigint, p_text text)
 returns boolean language plpgsql security definer set search_path to 'public' as $function$
begin
  if not public.darf_rufen() then raise exception 'not authorized'; end if;
  if length(trim(coalesce(p_text,''))) not between 1 and 5000 then raise exception 'text'; end if;
  update rufe_nachricht set text=p_text, bearbeitet_am=now()
   where id=p_id and autor=auth.uid() and archiviert_am is null;
  if not found then raise exception 'not authorized'; end if;
  return true;
end $function$;

-- ── 2. Bucket ───────────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('rufe-anhang', 'rufe-anhang', false, 10485760, array[
  'image/jpeg','image/png','image/webp','image/heic','application/pdf',
  'application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  'application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  'application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation'])
on conflict (id) do update set public=false, file_size_limit=excluded.file_size_limit, allowed_mime_types=excluded.allowed_mime_types;

-- Pfad: <raum_id>/<uuid>.<endung> – genau diese Form, sonst nichts (keine Unterordner, keine fremden Endungen)
create or replace function public.rufe_anhang_pfad_ok(p_pfad text) returns boolean
language sql immutable set search_path to 'public' as $$
  select coalesce(p_pfad ~ '^[0-9]{1,18}/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|jpeg|png|webp|heic|pdf|doc|docx|xls|xlsx|ppt|pptx)$', false);
$$;
create or replace function public.rufe_anhang_raum(p_pfad text) returns bigint
language sql immutable set search_path to 'public' as $$
  select case when public.rufe_anhang_pfad_ok(p_pfad) then split_part(p_pfad, '/', 1)::bigint end;
$$;

-- ── 3. Tabelle ──────────────────────────────────────────────────────────────────
create table if not exists public.rufe_anhang (
  id bigint generated by default as identity primary key,
  nachricht_id bigint not null references public.rufe_nachricht(id) on delete cascade,
  raum_id bigint not null references public.rufe_raum(id) on delete cascade,
  pfad text not null unique check (public.rufe_anhang_pfad_ok(pfad)),
  name text not null check (length(name) between 1 and 120),
  mime text not null check (mime in ('image/jpeg','image/png','image/webp','image/heic','application/pdf',
    'application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation')),
  groesse bigint not null check (groesse between 1 and 10485760),
  created_at timestamptz not null default now(),
  check (public.rufe_anhang_raum(pfad) = raum_id)
);
comment on table public.rufe_anhang is 'v736: Anhänge zu Adler-Rufen (Dateien im Bucket rufe-anhang). Lesen wie rufe_nachricht, schreiben nur der Autor, löschen nur Trainer.';
create index if not exists rufe_anhang_nachricht on public.rufe_anhang(nachricht_id);
alter table public.rufe_anhang enable row level security;

-- Raum muss zum Ruf passen, höchstens vier je Ruf, die Datei muss schon hochgeladen sein und dem Autor gehören.
create or replace function public.rufe_anhang_vor_insert() returns trigger
language plpgsql security definer set search_path to 'public' as $$
declare v_raum bigint; v_autor uuid;
begin
  select n.raum_id, n.autor into v_raum, v_autor from rufe_nachricht n where n.id = new.nachricht_id;
  if v_raum is null or v_raum <> new.raum_id then raise exception 'anhang raum'; end if;
  if (select count(*) from rufe_anhang a where a.nachricht_id = new.nachricht_id) >= 4 then raise exception 'hoechstens vier anhaenge'; end if;
  if not exists (select 1 from storage.objects o where o.bucket_id = 'rufe-anhang' and o.name = new.pfad
                 and (o.owner_id = v_autor::text or o.owner = v_autor)) then raise exception 'anhang datei'; end if;
  new.created_at := now();
  return new;
end $$;
drop trigger if exists rufe_anhang_vor on public.rufe_anhang;
create trigger rufe_anhang_vor before insert on public.rufe_anhang for each row execute function public.rufe_anhang_vor_insert();

drop policy if exists ra_lesen on public.rufe_anhang;
create policy ra_lesen on public.rufe_anhang for select to authenticated using (
  public.rufe_raum_sichtbar(raum_id)
  and exists (select 1 from public.rufe_nachricht n where n.id = nachricht_id and (n.archiviert_am is null or public.is_trainer())));
drop policy if exists ra_schreiben on public.rufe_anhang;
create policy ra_schreiben on public.rufe_anhang for insert to authenticated with check (
  public.rufe_raum_sichtbar(raum_id)
  and exists (select 1 from public.rufe_nachricht n where n.id = nachricht_id and n.raum_id = raum_id
              and n.autor = auth.uid() and n.archiviert_am is null));
drop policy if exists ra_loeschen on public.rufe_anhang;
create policy ra_loeschen on public.rufe_anhang for delete to authenticated using (public.is_trainer());
-- kein UPDATE: Anhänge werden nie geändert
revoke all on public.rufe_anhang from anon;
grant select, insert, delete on public.rufe_anhang to authenticated;

-- Liegt für einen Pfad schon eine Zeile? (ohne RLS – für die Löschregel im Speicher)
create or replace function public.rufe_anhang_vergeben(p_pfad text) returns boolean
language sql stable security definer set search_path to 'public' as $$
  select exists (select 1 from rufe_anhang a where a.pfad = p_pfad);
$$;
-- Darf der Anfragende die Datei lesen? Dieselbe Regel wie die Tabelle (Raum sichtbar, Ruf nicht archiviert außer Trainer).
create or replace function public.rufe_anhang_lesbar(p_pfad text) returns boolean
language sql stable security definer set search_path to 'public' as $$
  select exists (select 1 from rufe_anhang a join rufe_nachricht n on n.id = a.nachricht_id
                 where a.pfad = p_pfad and public.rufe_raum_sichtbar(a.raum_id) and (n.archiviert_am is null or public.is_trainer()));
$$;
revoke all on function public.rufe_anhang_vergeben(text) from public, anon;
revoke all on function public.rufe_anhang_lesbar(text) from public, anon;
grant execute on function public.rufe_anhang_vergeben(text) to authenticated;
grant execute on function public.rufe_anhang_lesbar(text) to authenticated;
grant execute on function public.rufe_anhang_pfad_ok(text) to authenticated;
grant execute on function public.rufe_anhang_raum(text) to authenticated;

-- ── Speicher-Regeln ─────────────────────────────────────────────────────────────
drop policy if exists "rufe-anhang hochladen" on storage.objects;
create policy "rufe-anhang hochladen" on storage.objects for insert to authenticated with check (
  bucket_id = 'rufe-anhang' and public.rufe_anhang_pfad_ok(name)
  and public.rufe_raum_sichtbar(public.rufe_anhang_raum(name))
  and coalesce(owner_id, owner::text) = auth.uid()::text);
drop policy if exists "rufe-anhang lesen" on storage.objects;
-- Trainer lesen alles (wie die Rufe selbst); der Besitzer liest seine eigene, noch nicht vergebene Datei –
-- ohne das kann er sie nach einem abgebrochenen Senden nicht wegräumen (Löschen setzt Lesen voraus).
create policy "rufe-anhang lesen" on storage.objects for select to authenticated using (
  bucket_id = 'rufe-anhang' and (public.rufe_anhang_lesbar(name) or public.is_trainer()
    or (coalesce(owner_id, owner::text) = auth.uid()::text and not public.rufe_anhang_vergeben(name))));
drop policy if exists "rufe-anhang loeschen" on storage.objects;
create policy "rufe-anhang loeschen" on storage.objects for delete to authenticated using (
  bucket_id = 'rufe-anhang' and (public.is_trainer()
    or (coalesce(owner_id, owner::text) = auth.uid()::text and not public.rufe_anhang_vergeben(name))));
-- kein UPDATE im Bucket (Dateien werden nie überschrieben)

-- ── 4. Senden in einem Schritt ──────────────────────────────────────────────────
create or replace function public.rufe_senden(p_raum bigint, p_text text, p_antwort_auf bigint default null,
                                              p_an_alle boolean default false, p_anhaenge jsonb default '[]'::jsonb)
 returns bigint language plpgsql security invoker set search_path to 'public' as $function$
declare v_id bigint; v_text text := trim(coalesce(p_text,'')); a jsonb;
begin
  if jsonb_typeof(coalesce(p_anhaenge,'[]'::jsonb)) <> 'array' then raise exception 'anhaenge'; end if;
  if jsonb_array_length(coalesce(p_anhaenge,'[]'::jsonb)) > 4 then raise exception 'hoechstens vier anhaenge'; end if;
  if v_text = '' and jsonb_array_length(coalesce(p_anhaenge,'[]'::jsonb)) > 0 then v_text := '📎 Anhang'; end if;
  insert into rufe_nachricht(raum_id, text, antwort_auf, an_alle)
  values (p_raum, v_text, p_antwort_auf, coalesce(p_an_alle,false)) returning id into v_id;
  for a in select * from jsonb_array_elements(coalesce(p_anhaenge,'[]'::jsonb)) loop
    insert into rufe_anhang(nachricht_id, raum_id, pfad, name, mime, groesse)
    values (v_id, p_raum, a->>'pfad', left(coalesce(a->>'name',''),120), a->>'mime', (a->>'groesse')::bigint);
  end loop;
  return v_id;
end $function$;
revoke all on function public.rufe_senden(bigint, text, bigint, boolean, jsonb) from public, anon;
grant execute on function public.rufe_senden(bigint, text, bigint, boolean, jsonb) to authenticated;

-- ── 5. Trainer löscht Anhänge endgültig ─────────────────────────────────────────
create or replace function public.rufe_anhaenge_loeschen(p_nachricht bigint)
 returns text[] language plpgsql security definer set search_path to 'public' as $function$
declare v_pfade text[];
begin
  if not public.is_trainer() then raise exception 'not authorized'; end if;
  with weg as (delete from rufe_anhang where nachricht_id = p_nachricht returning pfad)
  select coalesce(array_agg(pfad), '{}') into v_pfade from weg;
  if array_length(v_pfade, 1) > 0 then update rufe_nachricht set anhang_entfernt_am = now() where id = p_nachricht; end if;
  return v_pfade;
end $function$;
revoke all on function public.rufe_anhaenge_loeschen(bigint) from public, anon;
grant execute on function public.rufe_anhaenge_loeschen(bigint) to authenticated;
