-- v733 (Auftragspaket „Adler Nest als regelmäßige Ausgaben“, 03.10.2026): Das Adler Nest erscheint
-- nach jedem Spieltag als eigene, nummerierte Ausgabe und ist nur hinter dem Login lesbar – die
-- Elternfotos der Spieltagsgalerie haben keine Kind-Zuordnung und zeigen auch Gegnerkinder.
-- Lesen: Trainer alles; Team-Eltern und Kinder-Konten (PO 03.10.: „Ja, vollständig“) nur
-- Veröffentlichtes, und zwar nur über die Hüllfunktionen unten – so erreicht tag_quellen nie Eltern.
-- Schreiben: nur Trainer. anon: nichts.

-- 1) Ausgaben
create table if not exists public.heft_ausgabe (
  id bigint generated by default as identity primary key,
  team text not null default 'adler1',
  nummer int not null check (nummer > 0),
  termin_id bigint references public.termine(id) on delete set null,
  schlagzeile text check (schlagzeile is null or char_length(schlagzeile) <= 40),
  teaser_spieltag text check (teaser_spieltag is null or char_length(teaser_spieltag) <= 45),
  teaser_portraet text check (teaser_portraet is null or char_length(teaser_portraet) <= 45),
  teaser_tag text check (teaser_tag is null or char_length(teaser_tag) <= 45),
  titelbild_pfad text,
  audio_pfad text,
  audio_sekunden int check (audio_sekunden is null or audio_sekunden >= 0),
  anpfiff text,
  spieltag_text text,
  zitat text,
  eltern_dank text,
  sonderzeile text,
  foto_ids bigint[] not null default '{}' check (cardinality(foto_ids) <= 6),
  portraet_spieler_id bigint references public.kader(id) on delete set null,
  portraet_spitzname boolean not null default false,   -- Spitzname nur, wenn Charles ihn ausdrücklich will
  portraet_einleitung text,
  portraet_trainersatz text,
  portraet_privatfotos jsonb not null default '[]'::jsonb
    check (jsonb_typeof(portraet_privatfotos) = 'array' and jsonb_array_length(portraet_privatfotos) <= 2),
  training_leitfrage text,
  training_text text,
  tag_lernen text,
  tag_lustig text,
  tag_quellen text,
  kommentar text,
  status text not null default 'entwurf' check (status in ('entwurf','veroeffentlicht')),
  veroeffentlicht_am timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (team, nummer)
);
comment on table public.heft_ausgabe is 'v733: Adler Nest – eine Ausgabe je Spieltag; Eltern und Kinder lesen nur Veröffentlichtes über heft_ausgabe_lesen/heft_medien';
comment on column public.heft_ausgabe.tag_quellen is 'Quellen zu „An diesem Tag“ – nur für das Trainerteam, wird nie an Eltern ausgeliefert';
comment on column public.heft_ausgabe.portraet_privatfotos is 'bis 2 Einträge {pfad, unterschrift, einverstanden:true} im Bucket heft_media';

-- Privatfotos: jedes braucht Pfad, Unterschrift und das Einverständnis der Familie.
create or replace function public.heft_ausgabe_vor() returns trigger
language plpgsql set search_path to 'public' as $$
declare e jsonb;
begin
  for e in select * from jsonb_array_elements(coalesce(new.portraet_privatfotos,'[]'::jsonb)) loop
    if jsonb_typeof(e) <> 'object' or coalesce(e->>'pfad','') = '' then raise exception 'Privatfoto ohne Datei'; end if;
    if coalesce((e->>'einverstanden')::boolean, false) is not true then raise exception 'Privatfoto ohne Einverständnis der Familie'; end if;
  end loop;
  if new.status = 'veroeffentlicht' and new.veroeffentlicht_am is null then new.veroeffentlicht_am := now(); end if;
  if new.status = 'entwurf' then new.veroeffentlicht_am := null; end if;
  new.updated_at := now();
  return new;
end $$;
drop trigger if exists heft_ausgabe_vor on public.heft_ausgabe;
create trigger heft_ausgabe_vor before insert or update on public.heft_ausgabe
  for each row execute function public.heft_ausgabe_vor();

alter table public.heft_ausgabe enable row level security;
revoke all on public.heft_ausgabe from anon;
grant select, insert, update, delete on public.heft_ausgabe to authenticated;
drop policy if exists ha_trainer on public.heft_ausgabe;
create policy ha_trainer on public.heft_ausgabe for all to authenticated
  using (public.is_trainer()) with check (public.is_trainer());

-- 2) Fan-Fakten: starker Fuß, Saisonziel und der weitere Sport für den Steckbrief
alter table public.kind_fanfacts
  add column if not exists starker_fuss text,
  add column if not exists saisonziel text,
  add column if not exists weiterer_sport text,
  add column if not exists weiterer_sport_team text;
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'kind_fanfacts_starker_fuss_check') then
    alter table public.kind_fanfacts add constraint kind_fanfacts_starker_fuss_check
      check (starker_fuss is null or starker_fuss in ('links','rechts','beide'));
  end if;
end $$;

-- 3) Bucket heft_media (privat): Titelbild, Hördatei, Privatfotos des Porträts
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('heft_media','heft_media', false, 15728640, array['image/jpeg','image/png','image/webp','audio/mpeg','audio/mp3'])
on conflict (id) do nothing;

-- Sichtbar ist eine Datei, wenn sie zu einer veröffentlichten Ausgabe gehört (Trainer: immer).
-- security definer, damit die Prüfung nicht an der RLS von heft_ausgabe hängt (vgl. v731).
create or replace function public.heft_pfad_sichtbar(p_name text) returns boolean
language sql stable security definer set search_path to 'public' as $$
  select public.is_trainer() or (public.sitzung_gueltig() and exists (
    select 1 from public.heft_ausgabe a
    where a.status = 'veroeffentlicht'
      and (a.titelbild_pfad = p_name or a.audio_pfad = p_name
           or exists (select 1 from jsonb_array_elements(a.portraet_privatfotos) e where e->>'pfad' = p_name))));
$$;
revoke all on function public.heft_pfad_sichtbar(text) from public, anon;
grant execute on function public.heft_pfad_sichtbar(text) to authenticated;

drop policy if exists "heft_media lesen" on storage.objects;
create policy "heft_media lesen" on storage.objects for select to authenticated
  using (bucket_id = 'heft_media' and public.heft_pfad_sichtbar(name));
drop policy if exists "heft_media schreiben" on storage.objects;
create policy "heft_media schreiben" on storage.objects for insert to authenticated
  with check (bucket_id = 'heft_media' and public.is_trainer());
drop policy if exists "heft_media aendern" on storage.objects;
create policy "heft_media aendern" on storage.objects for update to authenticated
  using (bucket_id = 'heft_media' and public.is_trainer()) with check (bucket_id = 'heft_media' and public.is_trainer());
drop policy if exists "heft_media loeschen" on storage.objects;
create policy "heft_media loeschen" on storage.objects for delete to authenticated
  using (bucket_id = 'heft_media' and public.is_trainer());

-- 4) Hüllfunktionen (Muster v731: eine Prüfung vorn, dann die Daten)
-- Darf die laufende Sitzung diese Ausgabe sehen?
create or replace function public.heft_ausgabe_sichtbar(p_ausgabe bigint) returns boolean
language sql stable security definer set search_path to 'public' as $$
  select public.sitzung_gueltig() and exists (
    select 1 from public.heft_ausgabe a where a.id = p_ausgabe and (a.status = 'veroeffentlicht' or public.is_trainer()));
$$;
revoke all on function public.heft_ausgabe_sichtbar(bigint) from public, anon;
grant execute on function public.heft_ausgabe_sichtbar(bigint) to authenticated;

-- Pfade von Titelbild, Hördatei, Privatfotos und Galeriefotos (diese im Bucket termin_media).
create or replace function public.heft_medien(p_ausgabe bigint)
returns table(art text, bucket text, pfad text, unterschrift text, pos int)
language plpgsql stable security definer set search_path to 'public' as $$
declare a public.heft_ausgabe;
begin
  if not public.heft_ausgabe_sichtbar(p_ausgabe) then return; end if;
  select * into a from public.heft_ausgabe where id = p_ausgabe;
  if coalesce(a.titelbild_pfad,'') <> '' then return query select 'titelbild'::text, 'heft_media'::text, a.titelbild_pfad, null::text, 0; end if;
  if coalesce(a.audio_pfad,'') <> '' then return query select 'audio'::text, 'heft_media'::text, a.audio_pfad, null::text, 0; end if;
  return query select 'privat'::text, 'heft_media'::text, e.v->>'pfad', e.v->>'unterschrift', e.i::int
    from jsonb_array_elements(a.portraet_privatfotos) with ordinality e(v, i);
  return query select 'galerie'::text, 'termin_media'::text, m.foto_path, null::text, f.i::int
    from unnest(a.foto_ids) with ordinality f(id, i) join public.termin_media m on m.id = f.id order by f.i;
end $$;
revoke all on function public.heft_medien(bigint) from public, anon;
grant execute on function public.heft_medien(bigint) to authenticated;

-- Archiv: alle veröffentlichten Ausgaben, neueste zuerst.
create or replace function public.heft_ausgaben_liste()
returns table(id bigint, nummer int, datum text, typ text, titel text, gegner text, heim boolean, veroeffentlicht_am timestamptz)
language plpgsql stable security definer set search_path to 'public' as $$
begin
  if not public.sitzung_gueltig() then return; end if;
  return query select a.id, a.nummer, t.datum, t.typ, t.titel, t.gegner, t.heim, a.veroeffentlicht_am
    from public.heft_ausgabe a left join public.termine t on t.id = a.termin_id
    where a.status = 'veroeffentlicht' and a.team = 'adler1'
    order by a.nummer desc;
end $$;
revoke all on function public.heft_ausgaben_liste() from public, anon;
grant execute on function public.heft_ausgaben_liste() to authenticated;

-- Vorname und Initiale des Nachnamens (der Kader führt meist nur Vornamen).
create or replace function public.heft_name(p text) returns text
language sql immutable set search_path to 'public' as $$
  select case when array_length(regexp_split_to_array(trim(coalesce(p,'')), '\s+'), 1) > 1
    then split_part(trim(p), ' ', 1) || ' ' || upper(left((regexp_split_to_array(trim(p), '\s+'))[array_length(regexp_split_to_array(trim(p), '\s+'), 1)], 1)) || '.'
    else trim(coalesce(p,'')) end;
$$;

-- Eine Ausgabe mit allem, was die Leseansicht braucht – Spieltagskarte, Teams und Kapitäne aus den
-- App-Daten, Porträt aus Fan-Fakten und freigegebenen Reporter-Antworten. Nie: tag_quellen,
-- nummer_grund, Geburtsdatum; Spitzname nur mit portraet_spitzname; Jahrgang nur mit der Freigabe
-- „öffentlich“ (foto_stadionheft_ok), das Spielerfoto nur mit interner Foto-Freigabe.
create or replace function public.heft_ausgabe_lesen(p_ausgabe bigint) returns jsonb
language plpgsql stable security definer set search_path to 'public' as $$
declare
  a public.heft_ausgabe; t public.termine; v_datum text; v_nom jsonb; v_teams jsonb;
  v_team_liste jsonb := '[]'::jsonb; v_ergebnisse jsonb; v_portraet jsonb; v_naechster jsonb;
  k public.kader; f public.kind_fanfacts; n int; v_kap text; v_kinder jsonb; v_foto boolean;
begin
  if not public.heft_ausgabe_sichtbar(p_ausgabe) then return null; end if;
  select * into a from public.heft_ausgabe where id = p_ausgabe;
  if a.termin_id is not null then select * into t from public.termine where id = a.termin_id; end if;
  v_datum := t.datum;

  if v_datum is not null then
    select data::jsonb into v_nom from public.nominierungen where datum = v_datum || '__nom';
    select data::jsonb into v_teams from public.nominierungen where datum = v_datum || '__teams';
    n := coalesce((v_teams->>'_anzahl')::int, 0);
    if v_teams is null or n < 1 then n := 1; end if;
    for i in 1..n loop
      select ma.spieler into v_kap from public.match_actions ma
        where ma.aktion = 'kapitaen' and ma.datum = case when i = 1 then v_datum else v_datum || '__t' || i end
        order by ma.created_at desc limit 1;
      -- Kinder des Teams: wer dort eingeteilt ist (ohne Einteilung: alle, die „dabei“ sind) und „dabei“ ist.
      select coalesce(jsonb_agg(jsonb_build_object('name', public.heft_name(kd.name), 'nr', kd.nr,
               'kapitaen', (kd.name = v_kap)) order by (kd.name = v_kap) desc, kd.nr nulls last, kd.name), '[]'::jsonb)
        into v_kinder
        from public.kader kd
        where (case when v_teams is not null then v_teams->>(kd.id::text) = i::text else true end)
          and (v_nom is null or v_nom->>(kd.id::text) = 'dabei')
          and (v_teams is not null or v_nom is not null);
      v_team_liste := v_team_liste || jsonb_build_object('nr', i, 'kinder', v_kinder,
        'trainer', coalesce(v_teams->'_trainer'->(i::text), '[]'::jsonb));
    end loop;
    select coalesce(jsonb_agg(jsonb_build_object('team', coalesce(nullif(substring(s.datum from '__t(\d+)$'),'')::int, 1),
             'gegner', s.gegner, 'tore', s.tore, 'gegentore', s.gegentore) order by s.created_at), '[]'::jsonb)
      into v_ergebnisse from public.turnier_spiele s where s.datum = v_datum or s.datum like v_datum || '__t%';
  end if;

  if a.portraet_spieler_id is not null then
    select * into k from public.kader where id = a.portraet_spieler_id;
    select * into f from public.kind_fanfacts where spieler_id = a.portraet_spieler_id;
    v_foto := coalesce(f.gallery_optin, false) or exists (select 1 from public.foto_consent c where c.spieler_id = k.id and c.intern);
    v_portraet := jsonb_strip_nulls(jsonb_build_object(
      'name', public.heft_name(k.name), 'nr', k.nr, 'tw', k.tw,
      'position', nullif(k.lieblingsposition, ''),
      'jahrgang', case when k.foto_stadionheft_ok and k.geb is not null then extract(year from k.geb)::int end,
      'foto_pfad', case when v_foto then coalesce(nullif(k.foto_path,''), nullif(f.foto_path,'')) end,
      'spitzname', case when a.portraet_spitzname then nullif(f.spitzname,'') end,
      'starker_fuss', coalesce(nullif(f.starker_fuss,''), nullif(k.starker_fuss,'')),
      'adler_seit', nullif(f.adler_seit,''), 'lieblingsverein', nullif(f.lieblingsverein,''),
      'vorbild', nullif(f.lieblingsspieler,''), 'weiterer_sport', nullif(f.weiterer_sport,''),
      'weiterer_sport_team', nullif(f.weiterer_sport_team,''), 'hobby', nullif(f.hobby,''),
      'kann_gut', nullif(f.kann_gut,''), 'lieblingsessen', nullif(f.lieblingsessen,''),
      'lieblingstier', nullif(f.lieblingstier,''), 'lieblingsmusik', nullif(f.lieblingsmusik,''),
      'lieblingsfilm', nullif(f.lieblingsfilm,''), 'fussball_erlebnis', nullif(f.fussball_erlebnis,''),
      'gross_werden', nullif(f.gross_werden,''), 'saisonziel', nullif(f.saisonziel,''),
      'reporter', (select coalesce(jsonb_agg(jsonb_build_object('frage', r.frage, 'antwort', r.antwort) order by r.created_at), '[]'::jsonb)
                   from (select * from public.kabine_reporter r0 where r0.spieler_id = k.id and r0.freigegeben
                         order by r0.created_at desc limit 8) r)));
  end if;

  select jsonb_build_object('datum', x.datum, 'typ', x.typ, 'titel', x.titel, 'gegner', x.gegner, 'heim', x.heim,
           'uhrzeit', x.uhrzeit, 'treffzeit', x.treffzeit, 'ort', x.ort)
    into v_naechster from public.termine x
    where x.typ in ('spiel','turnier') and x.datum > coalesce(v_datum, to_char(now() at time zone 'Europe/Berlin','YYYY-MM-DD'))
    order by x.datum, x.uhrzeit nulls last limit 1;

  return jsonb_build_object(
    'ausgabe', to_jsonb(a) - 'tag_quellen' - 'portraet_privatfotos' - 'portraet_spitzname',
    'termin', case when t.id is null then null else jsonb_build_object('id', t.id, 'datum', t.datum, 'typ', t.typ,
      'titel', t.titel, 'gegner', t.gegner, 'heim', t.heim, 'ort', t.ort, 'uhrzeit', t.uhrzeit,
      'uhrzeit_ende', t.uhrzeit_ende, 'spielform', t.spielform, 'ergebnis', nullif(t.ergebnis,'')) end,
    'teams', v_team_liste, 'ergebnisse', coalesce(v_ergebnisse, '[]'::jsonb),
    'portraet', v_portraet, 'naechster', v_naechster);
end $$;
revoke all on function public.heft_ausgabe_lesen(bigint) from public, anon;
grant execute on function public.heft_ausgabe_lesen(bigint) to authenticated;

-- 5) Befund 03.10.: drei Probe-Aktionen vom 27.09. (Ticker-Test eine Woche vor dem Spieltag, bevor
--    das Kind als verletzt gemeldet war). PO 03.10.: „Probezeilen löschen“.
delete from public.match_actions where id in (37, 38, 39) and datum = '2026-10-03' and created_at < '2026-09-28';
